## Setup and Loading Data

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
train = pd.read_csv("Train.csv", index_col="Applicant_ID")

train.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50,default_status
Applicant_ID,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000000,3436.0,0.28505,1.6560,0.0,0.000,0.0,10689720.0,252072.0,4272776.0,11333126.0,...,0.392854,2.02,0.711632,0.0,0.0,charge,NaN,1.129518,0.044335,no
Apcnt_1000004,3456.0,0.67400,0.2342,0.0,0.000,0.0,898979.0,497531.0,9073814.0,2533168.0,...,0.314281,8.08,0.183584,NaN,0.0,charge,349.805730,1.620483,0.322436,no
Apcnt_1000008,3276.0,0.53845,3.1510,0.0,6.282,NaN,956940.0,NaN,192944.0,1079864.0,...,0.162965,18.18,0.791136,0.0,0.0,charge,NaN,1.513370,0.011640,yes
Apcnt_1000012,3372.0,0.17005,0.5050,0.0,0.000,192166.0,3044703.0,385499.0,3986472.0,3621979.0,...,0.488884,2.02,0.685168,NaN,0.0,charge,89.940100,0.664452,0.082729,no
Apcnt_1000016,3370.0,0.77270,1.1010,0.0,0.000,1556.0,214728.0,214728.0,1284089.0,361770.0,...,0.275000,12.12,0.438168,0.0,0.0,charge,97.887502,1.427891,0.045630,no

In [3]:
test = pd.read_csv("Test.csv", index_col="Applicant_ID")

test.head()

,form_field1,form_field2,form_field3,form_field4,form_field5,form_field6,form_field7,form_field8,form_field9,form_field10,...,form_field41,form_field42,form_field43,form_field44,form_field45,form_field46,form_field47,form_field48,form_field49,form_field50
Applicant_ID,,,,,,,,,,,,,,,,,,,,,
Apcnt_1000032,3236.0,0.34875,10.2006,0.0000,0.0,418564.0,418564.0,418564.0,540710.0,0.0,...,NaN,0.825000,1.01,0.800000,NaN,0.0,charge,NaN,0.000000,0.011221
Apcnt_1000048,3284.0,1.27360,2.9606,9.0198,0.0,0.0,9858816.0,49014.0,1510098.0,18308285.0,...,18.8415,0.507694,4.04,0.623248,1.0,0.0,lending,NaN,0.504974,0.043525
Apcnt_1000052,NaN,0.27505,0.0600,0.0000,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,0.00,NaN,NaN,NaN,charge,NaN,0.000000,NaN
Apcnt_1000076,3232.0,0.28505,2.8032,0.0000,0.0,0.0,473802.0,473802.0,1724437.0,493641.0,...,NaN,0.916663,2.02,0.464224,NaN,NaN,charge,90.163742,0.788809,0.104029
Apcnt_1000080,3466.0,2.09545,0.8318,2.5182,0.0,19839.0,1150662.0,1150662.0,7860523.0,5752921.0,...,NaN,0.234047,23.23,0.726688,0.0,0.0,lending,1303.587148,1.637733,0.163124

## EDA & Preprocessing

In [4]:
print("Train Shape:", train.shape)

train.info()

Train Shape: (56000, 51)
<class 'pandas.core.frame.DataFrame'>
Index: 56000 entries, Apcnt_1000000 to Apcnt_999996
Data columns (total 51 columns):
form_field1       53471 non-null float64
form_field2       52156 non-null float64
form_field3       55645 non-null float64
form_field4       55645 non-null float64
form_field5       55645 non-null float64
form_field6       42640 non-null float64
form_field7       50837 non-null float64
form_field8       42640 non-null float64
form_field9       47992 non-null float64
form_field10      55645 non-null float64
form_field11      24579 non-null float64
form_field12      46105 non-null float64
form_field13      50111 non-null float64
form_field14      56000 non-null int64
form_field15      33525 non-null float64
form_field16      42964 non-null float64
form_field17      44849 non-null float64
form_field18      45598 non-null float64
form_field19      55996 non-null float64
form_field20      55645 non-null float64
form_field21      40146 non-null float64
form_field22      35600 non-null float64
form_field23      27877 non-null float64
form_field24      42703 non-null float64
form_field25      50550 non-null float64
form_field26      48562 non-null float64
form_field27      46701 non-null float64
form_field28      55645 non-null float64
form_field29      55645 non-null float64
form_field30      30491 non-null float64
form_field31      16592 non-null float64
form_field32      50550 non-null float64
form_field33      54744 non-null float64
form_field34      55645 non-null float64
form_field35      32852 non-null float64
form_field36      54005 non-null float64
form_field37      50550 non-null float64
form_field38      55645 non-null float64
form_field39      51789 non-null float64
form_field40      12271 non-null float64
form_field41      17771 non-null float64
form_field42      54677 non-null float64
form_field43      55432 non-null float64
form_field44      50617 non-null float64
form_field45      24683 non-null float64
form_field46      40096 non-null float64
form_field47      56000 non-null object
form_field48      35111 non-null float64
form_field49      55645 non-null float64
form_field50      44944 non-null float64
default_status    56000 non-null object
dtypes: float64(48), int64(1), object(2)
memory usage: 22.2+ MB

In [5]:
print("Test shape:", test.shape)

test.info()

Test shape: (24000, 50)
<class 'pandas.core.frame.DataFrame'>
Index: 24000 entries, Apcnt_1000032 to Apcnt_999992
Data columns (total 50 columns):
form_field1     22890 non-null float64
form_field2     22291 non-null float64
form_field3     23854 non-null float64
form_field4     23854 non-null float64
form_field5     23854 non-null float64
form_field6     18396 non-null float64
form_field7     21769 non-null float64
form_field8     18396 non-null float64
form_field9     20600 non-null float64
form_field10    23853 non-null float64
form_field11    10602 non-null float64
form_field12    19817 non-null float64
form_field13    21537 non-null float64
form_field14    24000 non-null int64
form_field15    14408 non-null float64
form_field16    18526 non-null float64
form_field17    19305 non-null float64
form_field18    19631 non-null float64
form_field19    24000 non-null float64
form_field20    23853 non-null float64
form_field21    17293 non-null float64
form_field22    15276 non-null float64
form_field23    11875 non-null float64
form_field24    18395 non-null float64
form_field25    21744 non-null float64
form_field26    20828 non-null float64
form_field27    20090 non-null float64
form_field28    23853 non-null float64
form_field29    23853 non-null float64
form_field30    13092 non-null float64
form_field31    7190 non-null float64
form_field32    21744 non-null float64
form_field33    23505 non-null float64
form_field34    23853 non-null float64
form_field35    14134 non-null float64
form_field36    23097 non-null float64
form_field37    21744 non-null float64
form_field38    23853 non-null float64
form_field39    22171 non-null float64
form_field40    5172 non-null float64
form_field41    7651 non-null float64
form_field42    23422 non-null float64
form_field43    23750 non-null float64
form_field44    21638 non-null float64
form_field45    10462 non-null float64
form_field46    17115 non-null float64
form_field47    24000 non-null object
form_field48    15078 non-null float64
form_field49    23854 non-null float64
form_field50    19203 non-null float64
dtypes: float64(48), int64(1), object(1)
memory usage: 9.3+ MB

### Encoding other categorical variables

In [6]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

train.form_field47 = encoder.fit_transform(train.form_field47)
test.form_field47 = encoder.fit_transform(test.form_field47)

# encode the target variable
train.default_status = encoder.fit_transform(train.default_status)

In [7]:
# Separate target variable from predictors

y = train.pop('default_status')

# Checking for imbalance
y.value_counts()

0    42285
1    13715
Name: default_status, dtype: int64

### Initial Predictions

In [8]:
from catboost import CatBoostClassifier

cat_clf = CatBoostClassifier()

In [9]:
# cat_clf.fit(train, y)

In [10]:
# experimental_y_train = cat_clf.predict_proba(train)[:, 1]

# experimental_y_train = cat_clf.predict_proba(train)[:, 1]
# experimental_y_test = cat_clf.predict_proba(test)[:, 1]

In [11]:
# initializing y's for both train and test data

# train['y'] = experimental_y_train
# test['y'] = experimental_y_test

### Filling Missing Values

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

missing_val_predictor = RandomForestRegressor(n_estimators=100, n_jobs=-1)

imputer = IterativeImputer(estimator=missing_val_predictor)

In [ ]:
imputed_train = pd.DataFrame(imputer.fit_transform(train, y), columns=train.columns)
imputed_test = pd.DataFrame(imputer.transform(test), columns=test.columns)

### Setting up for modeling

In [ ]:
# dropping the experimental y's

# imputed_train.drop('y', axis=1, inplace=True)
# imputed_test.drop('y', axis=1, inplace=True)

# #check
# imputed_train.columns

In [ ]:
imputed_train.head()

## Feature Engineering & Selection

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

In [ ]:
# rf.fit(imputed_train, y)

In [ ]:
# feat_imp = rf.feature_importances_

# sorted(zip(imputed_train.columns, feat_imp), key=lambda x: x[1], reverse=True)

In [ ]:
# cols_to_drop = ['form_field4', 'form_field34',
#                 'form_field20', 'form_field39', 'form_field5']

# imputed_train.drop(cols_to_drop, 1, inplace=True)
# imputed_test.drop(cols_to_drop, 1, inplace=True)

## Modeling

In [ ]:
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

xgb_clf = XGBClassifier()
lgb_clf = LGBMClassifier()

In [ ]:
from sklearn.model_selection import cross_val_score

cv = cross_val_score(lgb_clf, imputed_train, y, cv=5)

In [ ]:
print(cv)

cv.mean()

## Final Steps

In [ ]:
final_clf = CatBoostClassifier()
final_clf.fit(imputed_train, y)

In [ ]:
test_pred = final_clf.predict_proba(imputed_test)[:, 1]

In [ ]:
submission = pd.read_csv("SampleSubmission.csv")

submission.sample()

In [ ]:
submission.default_status = test_pred

submission.head(1)

In [ ]:
submission.to_csv('sub_2.csv', index=False)